CREATE TABLE "users" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_users_by_email" ON "users" ("email");
